GSA/site-scanning-engine

- libs/core-scanner/src/core-scanner.service.spec.ts
- libs/core-scanner/src/core-scanner.service.ts
Why: Bugfix for the scanner base domain logic. 
Tags: bugfix, base domain ,scanner
> Fix base domain logic.

- apps/producer/src/task/task.service.ts
- manifest.yml
Why: This updates the `TaskService` and the `manifest.yml` to use the correct CRON configuration.
Tags: cron, task service, cf, manifest.yml
> Fix Scheduler Config.

- entities/solutions-result.entity.ts
- libs/solutions-scanner/src/solutions-scanner.service.spec.ts
- libs/solutions-scanner/src/solutions-scanner.service.ts
- libs/solutions-scanner/src/testPageSource.ts
- libs/solutions-scanner/test/app.e2e-spec.ts
Why: Add SEO and Search logic to the `SolutionsScannerService`. This looks for OpenGraph tags, robots.txt, sitemaps, and other fields that determine SEO and Searchability of a site. 
How: Add fields. Add tests. 
Tags: Solutions scanner, seo, open graph, testing
> Add SEO/Search Logic to Solutions Scanner.

- apps/api/src/website/website-serializer.interceptor.ts
- apps/api/src/website/website.controller.spec.ts
- libs/database/src/websites/websites.service.spec.ts
Why: This fixes a test that was failing, and adds a few new tests. 
Tags: Testing, Website Controller, Website service.
> Fix API test and add Website Service Tests.

- deploy-cloudgov.sh
Why: Adds `npm build` and `cf push` to deploy script. Moves around the status checking.
Tags: deploy, npm, cf
> Update deploy script.

- libs/database/src/database.module.ts
Why: Adding synchronize back until I can work on migrations. 
Tags: database, synchronize, migrations
> Add synchronize back.

- .github/workflows/test.yml
Why: Adds a CI Github Actions workflow.
Tags: CI, Github Actions
> Add test workflow.

- .github/workflows/test.yml
- libs/solutions-scanner/src/solutions-scanner.service.spec.ts
- package.json
Why: Updates the regex patterns for the unit and e2e tests. Updates a test that was failing.
Tags: CI, github actions
> Fix GitHub Actions CI

- README.md
- nest-cli.json
- package.json
Why: This change is mostly documentation along with a few workflow improvements, based on the handover to the team. 
How: This lowers the compilation time by limiting the Swagger boilerplate generation to the API only. It also runs `build:all` concurrently and adds the CLI to the build. 
Tags: documentation, workflow, npm scripts, swagger, open api
> Update development documentation and workflow

- libs/database/src/websites/websites.service.spec.ts
- libs/database/src/websites/websites.service.ts
Why: Update if the website exists. Otherwise, insert. 
Tags: website, insert, typeorm
> Update if website exists

- apps/scan-engine/src/scan-engine.consumer.ts
- manifest.yml
Why: Doing a bit of performance tuning. This brings down the instances but ups the concurrency. 
Tags: tuning.
> Change instances and Concurrency 

- README.md
- cloudgov-deploy.sh
- manifest-dev.yml
Add cloud.gov dev manifest (manifest-dev.yml) and update the README.
> Add dev manifest and update documentation.

- .github/workflows/deploy.yml
Make the cron list syntax work.
> Fix bug in GH Action syntax.

- .github/workflows/deploy.yml
Adds the ability to the run the deploy action from the Actions panel.
> Add workflow dispatch to run job from Actions panel.

- .github/workflows/deploy.yml
Reverts GSA/site-scanning-engine#112
> Revert "Experiment."

- .github/workflows/deploy.yml
Add push arguments to the cf deploy.
> Add push arguments

- .github/workflows/deploy.yml
- manifest.yml
Scale up to 4 instances after the initial deploy.
> Scale instances in GH Action

- cloudgov-run-ingest.sh
Add a `-c` to the command and increase the memory of the instance.
> Make script cf7 friendly and boost size of instance.

- libs/database/src/database.module.ts
From https://devcenter.heroku.com/articles/heroku-postgresql#connecting-in-node-js
> Remove prohibition against self-signed certs

- .github/workflows/deploy.yml
> Github Actions - Tweaks, bug-fixes, etc 

- .github/workflows/semgrep.yml
This is for [146](https://github.com/GSA/site-scanning/issues/146) (add semgrep workflow)
> Initial addition of semgrep action

- .pre-commit-config.yaml
This is for [145](https://github.com/GSA/site-scanning/issues/145) (add pre-commit configuration).
To use on your local system, run:
```sh
pip install -U pre-commit
pre-commit install
```
> Initial commit of pre-commit config

- .github/workflows/codeql.yml
This is an import of BEARS's CodeQL configuration (with a little cleanup).  
resolves GSA/site-scanning#158
> 158 codeql

- libs/core-scanner/src/scans/core.spec.ts
- libs/core-scanner/src/scans/seo.spec.ts
- libs/core-scanner/src/scans/uswds.spec.ts
- libs/core-scanner/src/test-helper.ts
Fix bad path to test fixture data.
> Fix mht root path

- .github/workflows/semgrep.yml
resolves GSA/site-scanning#185
> Generate and upload semgrep.sarif with security alerts

- .github/workflows/megalinter.yml
- .github/workflows/snyk.yml
- .github/workflows/woke.yml
- package-lock.json
This is a little tidying of GitHub actions (syntax, SARIF artifact uploads)
> Cleanup syntax

- .github/workflows/deploy.yml
Tweak Github deployment workflow to use scaling from the manifest and doa more basic single-command deploy.
> Deployment workflow debugging

- .github/workflows/deploy.yml
Debugging: use cg-cli-tools for "cf push", to skip the rolling deployment.
> Skip rolling deploy - deployment debugging

- entities/website.entity.ts
- libs/database/src/websites/dto/create-website.dto.ts
- libs/database/src/websites/websites.service.spec.ts
- libs/database/src/websites/websites.service.ts
- libs/ingest/src/ingest.service.ts
- libs/ingest/src/subdomain-row.interface.ts
These changes fix a bug in the ingest service that prevented three boolean fields from being imported correctly.
> Website field fix

- libs/core-scanner/src/pages/extractors.ts
- libs/core-scanner/src/pages/primary.ts
Issue: https://github.com/GSA/site-scanning/issues/200
Changes: Add error handling to the `createCSSRequestsExtractor` function, which contains an async call to the Puppeteer `HTTPResponse` class's `text` method.
> Handle extractors error

- libs/core-scanner/src/pages/primary.spec.ts
- libs/core-scanner/src/scans/required-links.ts
Update regex searching for text within anchor elements to ignore newline characters.
> Update hasStringInLinkText regex

- libs/core-scanner/src/pages/primary.ts
- libs/core-scanner/src/scans/dap.spec.ts
- libs/core-scanner/src/scans/dap.ts
This PR adds logging to the DAP scan.
> Dap logging

- libs/core-scanner/src/pages/primary.spec.ts
- libs/storage/src/config/storage.config.ts
- libs/storage/src/storage.service.ts
- package-lock.json
- package.json
This PR updates the `aws-sdk` dependency from v2 to v3. It also updates a test that makes a network request to https://18f.gsa.gov.
> Storage lib update

- libs/database/src/websites/websites.service.integration.spec.ts
- libs/database/src/websites/websites.service.ts
Remove logic filter out .mil sites from API and snapshot.
> Remove filters for dot mil sites

- libs/core-scanner/src/core-scanner.service.ts
- libs/core-scanner/src/pages/accessibility.ts
Update a11y scan to handle cases where no results were found. Refactor scan.
> a11y logging

- libs/core-scanner/src/pages/accessibility.ts
Update method of loading HTMLCS into page context
> a11y update

- libs/core-scanner/src/pages/accessibility.ts
Wait for page navigagtion only if necessary.
> a11y scan update

- entities/core-result.entity.ts
- entities/scan-data.entity.ts
- libs/core-scanner/src/pages/primary.spec.ts
- libs/core-scanner/src/pages/primary.ts
- libs/core-scanner/src/scans/seo.spec.ts
- libs/core-scanner/src/scans/seo.ts
- libs/database/src/core-results/core-result.service.spec.ts
- libs/database/src/core-results/core-result.service.ts
Per https://github.com/GSA/site-scanning/issues/730, add three new fields and update the logic for canonical URL scan.
> Add new seo fields

- entities/core-result.entity.ts
- entities/scan-data.entity.ts
- entities/scan-page.entity.ts
- libs/core-scanner/src/core-scanner.service.ts
- libs/core-scanner/src/pages/index.ts
- libs/core-scanner/src/pages/performance.ts
- libs/database/src/core-results/core-result.service.spec.ts
- libs/database/src/core-results/core-result.service.ts
Implement first iteration of performance scan, calculating Largest Contentful Paint (LCP) and Cumulative Layout Shift (CLS).
> First iteration of performance scan

- entities/website.entity.ts
- libs/database/src/analysis/analysis.service.integration.spec.ts
- libs/database/src/websites/dto/create-website.dto.ts
- libs/database/src/websites/websites.service.integration.spec.ts
- libs/database/src/websites/websites.service.spec.ts
- libs/database/src/websites/websites.service.ts
- libs/ingest/src/ingest.module.ts
- libs/ingest/src/ingest.service.spec.ts
- libs/ingest/src/ingest.service.ts
- libs/ingest/src/subdomain-row.interface.ts
- libs/ingest/src/url-list-data-fetcher.spec.ts
- libs/ingest/src/url-list-data-fetcher.ts
Update ingest module and website entity, services etc. to handle new data sources and new field.
> Ingest Update

- libs/core-scanner/src/pages/accessibility/results-aggregator.ts
Update logic that tallies number of violations in a11y scan per https://github.com/GSA/site-scanning/issues/932
> a11y results summary update

- entities/core-result.entity.ts
- entities/scan-data.entity.ts
- libs/core-scanner/src/core-scanner.service.spec.ts
- libs/database/src/core-results/core-result.service.spec.ts
- libs/database/src/core-results/core-result.service.ts
- libs/security-data/src/security-data.service.spec.ts
- libs/security-data/src/security-data.service.ts
- Change field name from `hstsPreloaded` to `hsts`
- Change logic calculating whether `hsts` is true or false for a given URL
> Update security scan logic

- entities/core-result.entity.ts
- entities/scan-data.entity.ts
- libs/core-scanner/src/scans/dap.spec.ts
- libs/core-scanner/src/scans/dap.ts
- libs/database/src/core-results/core-result.service.spec.ts
- libs/database/src/core-results/core-result.service.ts
Relates to GSA/site-scanning#1108
> Prototype GA Tag Scan

- entities/core-result.entity.ts
Relates to GSA/site-scanning#875
> Expose dap_version field

- libs/core-scanner/src/scans/dap.spec.ts
- libs/core-scanner/src/scans/dap.ts
Relates to GSA/site-scanning#1121
> Update tag scan

- entities/core-result.entity.ts
Relates to GSA/site-scanning#1108
> Expose GA Tags

- libs/core-scanner/src/pages/accessibility/results-aggregator.spec.ts
- libs/core-scanner/src/pages/accessibility/results-aggregator.ts
Relates to GSA/site-scanning#1063
> Add scan date/time to a11y scan

- libs/core-scanner/src/scans/dap.spec.ts
- libs/core-scanner/src/scans/dap.ts
Relates to GSA/site-scanning#1107
> Add logging to DAP scan

- libs/core-scanner/src/scans/dap.ts
Relates to GSA/site-scanning#1107
> Update logging metrics

- libs/core-scanner/src/scans/dap.spec.ts
- libs/core-scanner/src/scans/dap.ts
- libs/core-scanner/src/test-helper.ts
- package.json
- test/jest.setup.ts
Relates to GSA/site-scanning#1132
> DAP Scan Updates

- libs/core-scanner/src/scans/dap.spec.ts
- libs/core-scanner/src/scans/dap.ts
Relates to GSA/site-scanning#1132
> Revert DAP logic changes

- entities/core-result.entity.ts
- entities/scan-data.entity.ts
- libs/core-scanner/src/metric-utils.spec.ts
- libs/core-scanner/src/metric-utils.ts
- libs/core-scanner/src/pages/primary.ts
- libs/core-scanner/src/scans/third-party.spec.ts
- libs/core-scanner/src/scans/third-party.ts
- libs/database/src/core-results/core-result.service.spec.ts
- libs/database/src/core-results/core-result.service.ts
Relates to GSA/site-scanning#1139
> Third Party Services URLs

- libs/core-scanner/src/scans/third-party.ts
Relates to GSA/site-scanning#1139
> 1339: Filter out file load URLs

- entities/core-result.entity.ts
- libs/core-scanner/src/scans/third-party.ts
- libs/snapshot/src/serializers/json-serializer.spec.ts
Relates to GSA/site-scanning#1157
> Update filtering and expose URLs field

- libs/database/src/config/db.config.ts
Relates to GSA/site-scanning#1143
> 1143: Switch to new database

- libs/core-scanner/src/scans/third-party.ts
- libs/core-scanner/src/scans/uswds.spec.ts
- libs/core-scanner/src/scans/uswds.ts
Relates to GSA/site-scanning#1146
> Add check for Spanish: Here's how you know banner

- libs/core-scanner/src/scans/uswds.ts
Relates to GSA/site-scanning#1146
> 1146: Update metrics logging

- libs/core-scanner/src/metric-utils.ts
- libs/core-scanner/src/pages/primary.ts
- libs/core-scanner/src/scans/dap.ts
- libs/core-scanner/src/scans/third-party.ts
Relates to GSA/site-scanning#1172
> Add additional logging metrics to scans

- libs/core-scanner/src/pages/primary.ts
- libs/core-scanner/src/scans/cms.spec.ts
- libs/core-scanner/src/scans/cms.ts
- libs/core-scanner/src/scans/cookies.spec.ts
- libs/core-scanner/src/scans/cookies.ts
- libs/core-scanner/src/scans/login.spec.ts
- libs/core-scanner/src/scans/login.ts
- libs/core-scanner/src/scans/required-links.spec.ts
- libs/core-scanner/src/scans/required-links.ts
- libs/core-scanner/src/scans/search.spec.ts
- libs/core-scanner/src/scans/search.ts
- libs/core-scanner/src/scans/uswds.spec.ts
- libs/core-scanner/src/scans/uswds.ts
Relates to GSA/site-scanning#1172
> 1172: Update run wrapper to include logger

- libs/core-scanner/src/metric-utils.spec.ts
- libs/core-scanner/src/metric-utils.ts
- libs/core-scanner/src/scans/dap.ts
- libs/core-scanner/src/util.spec.ts
- libs/core-scanner/src/util.ts
Relates to GSA/site-scanning#1172
> 1172: Added additional logging metrics

- libs/browser/src/browser.service.ts
- libs/browser/src/puppeteer-pool.ts
##Purpose
Implement additional logging metrics and error handling functionality.
> Error Handling/Logging Improvements

- apps/cli/src/main.ts
- apps/cli/src/queue.controller.ts
- libs/core-scanner/src/core-scanner.service.ts
Update the url logging field to ensure application logs are ingested into Logstash properly. Also added a cli command for checking the queue status.
> Improve logging metrics

- libs/core-scanner/src/pages/primary.ts
Update the network idle timeout within the primary scanner.
> Update try/catch logic within the primary scanner

- libs/core-scanner/src/scans/dap.ts
- libs/core-scanner/src/util.spec.ts
- libs/core-scanner/src/util.ts
Change the response log message to be more useful.
> Adjust response log messages

- package-lock.json
- package.json
Update the @axe-core/puppeteer package. This cleared up a few errors on local runs.
> Update @axe-core/puppeteer package

- apps/cli/src/queue.controller.ts
- libs/core-scanner/src/scans/cms.ts
- libs/core-scanner/src/scans/login.ts
- libs/core-scanner/src/scans/mobile.ts
- libs/core-scanner/src/scans/required-links.ts
- libs/core-scanner/src/scans/search.ts
- libs/core-scanner/src/scans/seo.ts
- libs/core-scanner/src/scans/third-party.ts
- libs/core-scanner/src/scans/uswds.ts
- package-lock.json
- package.json
Implement additional error handling within the Primary Scans to resolve scanner crashes when a site's content cannot be loaded properly.
> Resolve Primary Scan crashes

- libs/browser/src/browser.service.ts
Properly handle crashes within the page processor.
> Improve error handling in the page processor

- apps/scan-engine/src/scan-engine.consumer.ts
Add queue status and memory usage logging within the scan-engine.
> Add queue status and memory  usage logging

- apps/scan-engine/src/scan-engine.consumer.ts
- libs/browser/src/browser.service.ts
- libs/core-scanner/src/core-scanner.service.ts
- libs/core-scanner/src/pages/primary.ts
- libs/core-scanner/src/scans/cms.ts
- libs/core-scanner/src/scans/login.ts
- libs/core-scanner/src/scans/mobile.ts
- libs/core-scanner/src/scans/required-links.ts
- libs/core-scanner/src/scans/search.ts
- libs/core-scanner/src/scans/seo.ts
- libs/core-scanner/src/scans/uswds.ts
- libs/core-scanner/src/util.ts
Revert recent updates to logging metadata and error-handling methods.
> Revert recent changes

- vars-prod.yml
This PR updates the configuration to increase the allocated disk space. The change addresses the need for additional storage capacity to support growing data requirements and ensure smooth operation of the application.
> Increase Disk Space Allocation in Configuration

- libs/browser/src/puppeteer.service.ts
- package-lock.json
- package.json
This pull request updates the Puppeteer dependency to version 23.8.0. Along with the upgrade, I’ve addressed and refactored deprecated code that was causing issues with compatibility in the previous version.
> Update Puppeteer to v23.8.0 and Resolve Deprecated Code Issues

- libs/browser/src/puppeteer.service.ts
- package-lock.json
- package.json
Reverts GSA/site-scanning-engine#407
> Revert "Update Puppeteer to v23.8.0 and Resolve Deprecated Code Issues"

- libs/browser/src/puppeteer-pool.ts
- libs/browser/src/puppeteer.service.ts
- package-lock.json
- package.json
Update puppeteer to latest version.
> Update puppeteer to 23.8.0

- vars-dev.yml
This pull request increases the disk space allocation for our consumer application to address and eliminate recurring "out of disk space" errors. The current disk capacity has been insufficient to handle the growing data usage, leading to failures in application deployment.
> Increase Disk Space Allocation for Consumer Application

- apps/api/src/pagination-request.dto.ts
Fix bug that occurred due to updating the *class-transformer* package.
> Update pagination transform function

- entities/core-result.entity.ts
Expose the accessibility_violations field to the snapshot and API
> Expose Accessibility field

- entities/core-result.entity.ts
- entities/scan-data.entity.ts
- entities/scan-page.entity.ts
- libs/core-scanner/src/core-scanner.service.ts
- libs/core-scanner/src/pages/types.ts
- libs/core-scanner/src/pages/www.ts
- libs/database/src/core-results/core-result.service.spec.ts
- libs/database/src/core-results/core-result.service.ts
Enable the **www scan** and expose the output values to the snapshot
> Enable WWW Scan and Expose Output to Snapshot
