GSA/site-scanning-engine

.cfignore
apps/api/src/main.ts
deploy-cloudgov.sh
libs/database/src/config/db.config.ts
libs/database/src/database.module.ts
manifest.yml
package.json

**Why**: This adds the site-scanning-api to Cloud.gov.
**How**: Add a deploy-cloudgov.sh script which (currently) only creates the
services necessary. Note that there is some logic in the script that
checks if Postgres is created, but I just read that this logic is
actually incorrect! I'll update in the next PR.
Add a manifest.yml to specify the api name and how
to run it -- this also binds the postgres RDS instance to the
application.
Lastly, update the database configuration so that we pull in the
credentials using the ConfigService.
**tags**: postgres, cloud.gov, config, api

Add API to Cloud.gov

---

docker-compose.yml

Why: Removing the app services from docker-compose as I'm just using `npm` to run the apps currently.
How: Updating the `docker-compose.yml` file. 
Tags: docker, compose, local dev, npm

Simplify docker-compose

---

apps/producer/src/producer.module.ts
apps/producer/src/task/task.service.spec.ts
apps/producer/src/task/task.service.ts
apps/scanner/src/scan-engine/scan-engine.consumer.spec.ts
apps/scanner/src/scan-engine/scan-engine.consumer.ts
apps/scanner/src/scan-engine/scan-engine.module.ts
libs/logger/src/index.ts
libs/logger/src/logger.module.ts
libs/logger/src/logger.service.spec.ts
libs/logger/src/logger.service.ts
libs/logger/tsconfig.lib.json
nest-cli.json
package.json
tsconfig.json

Why: Add a custom logger to the application. 
How: I am creating a `LoggerModule` in the `libs` directory. This way we can use the same logger in the different applications. 
Tags: logging, library, libs, custom

Add logger

---

apps/scan-engine/src/scan-engine.consumer.spec.ts
apps/scan-engine/src/scan-engine.consumer.ts
common/dtos/scanners/core.output.dto.ts
libs/core-scanner/src/core-scanner.module.ts
libs/core-scanner/src/core-scanner.service.spec.ts
libs/core-scanner/src/core-scanner.service.ts
libs/database/src/core-results/core-result.entity.ts
libs/database/src/core-results/core-result.service.spec.ts
libs/database/src/core-results/core-result.service.ts
libs/database/src/core-results/dto/create-core-result.dto.ts
libs/database/src/database.module.ts

**Why**: This adds the basic fields to the `CoreScanner` and updates the `CoreResult` entity and related services to use the new data. 
**How**: Update `CoreResult` entity, update the `CoreResult` service, and update the `CoreScanner`. 
**Tags**: core, scanner

Add basic fields to scanner

---

apps/producer/src/task/task.service.ts
libs/database/src/core-results/core-result.service.ts

Why: Updating the `CoreResultService` to do updates when a row exists. 
Tags: core results, postgres, typeorm

Update CoreResult service to do database updates when row exists

---

libs/core-scanner/src/core-scanner.service.spec.ts
libs/core-scanner/src/core-scanner.service.ts

Why: I believe not calling `page.close` was causing a memory leak. This closes the a page after the scan. 
How: Add the `page.close` call in the `CoreScanner`. Add test to check that it is called.
Tags: puppeteer, memory leak, memory, core, core scanner

Close the puppeteer page after scanning.

---

apps/cli/src/app.module.ts
apps/cli/src/ingest.controller.spec.ts
apps/cli/src/ingest.controller.ts
apps/cli/src/main.ts
apps/cli/test/app.e2e-spec.ts
apps/cli/test/jest-e2e.json
apps/cli/tsconfig.app.json
docs/layout.md
libs/core-scanner/src/core-scanner.service.ts
libs/database/src/websites/dto/create-website.dto.ts
libs/database/src/websites/website.entity.ts
libs/database/src/websites/website.module.ts
libs/database/src/websites/websites.service.spec.ts
libs/database/src/websites/websites.service.ts
libs/ingest/src/index.ts
libs/ingest/src/ingest.module.ts
libs/ingest/src/ingest.service.spec.ts
libs/ingest/src/ingest.service.ts
libs/ingest/tsconfig.lib.json
nest-cli.json
package-lock.json
package.json
tsconfig.json

**Why**: We need a way to repeatably add target urls for the scanner to scan. This commit adds a few things in service of that goal: 
- An `IngestService` that can be used for any kind of data ingest into the
system. In this commit it is used to add target urls to the Website table which the scanner consumes.
- A general-purpose `CLI` for the site-scanner. In this commit it is being used to call
the `IngestService` and add target urls to the scanner.
- Updates to the `Website` model to include new fields from the GSA dataset. 
- A fix to the `CoreScanner` to prepend "https" to the target url.
**Tags**: target urls, core scanner, ingest, cli, docs

Add initial Target URL generation capability

---

apps/cli/src/ingest.controller.ts
apps/cli/src/main.ts
libs/ingest/src/ingest.service.ts

Why: For local dev purposes, add a dev option to the CLI to avoid ingesting all of the federal urls.

Add a dev option to the Ingest cli app.

---

entities/core-result.entity.ts
libs/core-scanner/src/core-scanner.module.ts
libs/core-scanner/src/core-scanner.service.spec.ts
libs/core-scanner/src/core-scanner.service.ts
package-lock.json
package.json

Why: This tests that a `target_url` returns a 404 when given a page that doesn't exist. The current methodology is just to add a path `not_found_test_{uuid}` with a random uuid generated. 
How: Add an axios get call to the core scanner. Add tests.
Tags: core scanner, not found test, uuid, 404

Add 404 Test.

---

libs/core-scanner/src/core-scanner.service.ts

Why: The `axios` library throws an exception on 404s. This changes it to not do that through a configuration option. 
Tags: bug fix, axios, 404 test

Fix 404 test bug.

---

apps/producer/src/producer/producer.service.ts
apps/producer/src/task/task.service.ts

Why: Empty the queue on start. This ensures that we're not using stale job data with incorrect website ids.
How: Call the `empty` and `clean` methods from the `bull` redis library.
Tags: bull, queue, empty, clean

Empty queue on start

---

libs/core-scanner/src/core-scanner.service.ts

Why: We were getting a lot of dns resolution errors that were actually SSL errors. This adds the SSL error detection.
Tags: SSL, core scanner

Add SSL error

---

entities/uswds-result.entity.ts
libs/uswds-scanner/src/index.ts
libs/uswds-scanner/src/uswds-scanner.module.ts
libs/uswds-scanner/src/uswds-scanner.service.spec.ts
libs/uswds-scanner/src/uswds-scanner.service.ts
libs/uswds-scanner/src/uswds.input.dto.ts
libs/uswds-scanner/test/app.e2e-spec.ts
libs/uswds-scanner/test/jest-e2e.json
libs/uswds-scanner/tsconfig.lib.json
nest-cli.json
package.json
tsconfig.json

**Why**: This adds a scanner and entity specifically for USWDS scans. This adapts Domain Scan's [USWDS2 scanner](https://github.com/18F/domain-scan/blob/master/scanners/uswds2.py). The basic idea behind this scanner is to heuristically determine the presence of USWDS on given website. It checks for the various characteristics that would likely be present on a site using USWDS and weights them accordingly. 
**How**: Add a new library `uswds-scanner` which implements the scanner interface. Add a new entity `uswds-result.entity.ts` which captures all of the fields. and various serialization methods.
Tags: uswds, scanner, entity, heuristic

Add USWDS Scan

---

apps/api/src/app.module.ts
apps/api/src/website/serializer.ts
apps/api/src/website/website.controller.spec.ts
apps/api/src/website/website.controller.ts
apps/producer/src/producer/producer.service.ts
apps/producer/src/task/task.service.ts
apps/scan-engine/src/app.module.ts
apps/scan-engine/src/scan-engine.consumer.spec.ts
apps/scan-engine/src/scan-engine.consumer.ts
entities/core-result.entity.ts
entities/uswds-result.entity.ts
entities/website.entity.ts
libs/browser/src/browser.service.ts
libs/core-scanner/src/core-scanner.service.ts
libs/database/src/core-results/core-result.module.ts
libs/database/src/database.module.ts
libs/database/src/uswds-result/uswds-result.module.ts
libs/database/src/uswds-result/uswds-result.service.spec.ts
libs/database/src/uswds-result/uswds-result.service.ts
libs/database/src/websites/websites.service.ts
libs/message-queue/src/message-queue.module.ts
libs/uswds-scanner/src/uswds-scanner.service.spec.ts
libs/uswds-scanner/src/uswds-scanner.service.ts
libs/uswds-scanner/test/app.e2e-spec.ts

Why: This adds the USWDS scan data to the API. I made a few changes in design to accommodate this.
1) The big change is querying `Websites` instead of `CoreResults` and joining `CoreResult` and `UswdsResult` to `Websites`. I added bi-directional OneToOne fields on the results and on Website. This way we can maintain the simple serialization at the API edge. 
2) I added another `Job` type to the producer and consumer. With this we can scan for USWDS on a different schedule than the CoreScanner, if we wish. 
3) I added error handling to the `UswdsScannerService` so it will actually complete now (even if there's errors!)
The rest of the changes are mostly dependency injection simplification (where I saw it could be refactored) and tests.
Tags: uswds, tests, DI, dependency injection

Add USWDS to API results

---

apps/cli/src/ingest.controller.ts
apps/cli/src/main.ts

Why: This adds a `--limit <number>` to the ingest tool and removes the `--dev` flag. 
Tags: ingest

Add limit option to ingest.

---

package.json

Why: Need to use LTS (currently 14.x.x) to support the new string methods (`matchAll`).
How: Update the `package.json` to include an `engine` field. 
Tags: cloud foundry, node, version

Add node version for Cloud Foundry

---

entities/solutions-result.entity.ts
libs/solutions-scanner/src/solutions-scanner.service.spec.ts
libs/solutions-scanner/src/solutions-scanner.service.ts
libs/solutions-scanner/test/app.e2e-spec.ts

Why: This adds the USWDS version fields to the Solutions scanner. This looks in CSS for the first USWDS version it can find (using RegEx) and returns the version. It also adds 20 points to the USWDS Detection heuristic. 
How: Add fields to the scanner and the data model. Add tests.
Tags: uswds, semantic version, solutions scanner

Add USWDS version fields

---

libs/core-scanner/src/core-scanner.service.ts

Why: Await `page.close` in the core scanner.

Await page close.

---

libs/browser/src/browser.service.ts
libs/core-scanner/test/app.e2e-spec.ts

Why: Filling out the SSL errors. Fixed a test that was not tearing down correctly. 
Tags: errors, testing

Add SSL error and Fix Leaky Test

---

libs/core-scanner/src/core-scanner.module.ts
libs/core-scanner/src/core-scanner.service.ts
libs/core-scanner/test/app.e2e-spec.ts
package.json

Why: There is inconsistency in the data, because we are using Axios for the 404 test and Axios throws an SSL error when it can't verify a certificate chain. For now, disable checking that. Add a test for a website that has an incomplete chain. 
Tags: axios, 404 test, testing, SSL, certificate chain

Ignore SSL errors from Axios.

---

libs/core-scanner/src/core-scanner.service.ts
libs/solutions-scanner/src/solutions-scanner.service.ts

Why: Disables the Puppeteer page cache to avoid 304 status codes. Closes https://github.com/18F/site-scanning/issues/811
Tags: scanning, cache

Disable the Puppeteer page cache.

---

libs/database/src/database.module.ts

Why: The schema is at a point where dropping the tables and synchronizing is no longer necessary! 🎉 
How: Remove from the database initialization step. 
Tags: DB

Remove the dev schema drop.

---

apps/api/src/main.ts
apps/api/src/website/website.controller.spec.ts
apps/api/src/website/website.controller.ts
entities/core-result.entity.ts
libs/database/src/websites/dto/filter-website.dto.ts
libs/database/src/websites/websites.service.ts

Why: This is query parameters to the API for the following fields: 
- Target URL (path parameter)
- `target_url_domain`
- `final_url_domain`
- `final_url_live`
- `target_url_redirects`
- `target_url_agency_owner`
- `target_url_bureau_owner`
- `scan_status`
- `dap_detected_final_url`
It also adds query parameter validation using the `class-validator` and a `FilterWebsiteDto` data transfer object.
Tags: API, filters, query, validation

Add Query Filters to API

---

apps/api/src/website/website-serializer.interceptor.ts
apps/api/src/website/website.controller.spec.ts
apps/api/src/website/website.controller.ts
libs/database/src/websites/websites.service.ts
manifest.yml
package-lock.json
package.json

Why: This adds pagination to the API using the `nestjs-typeorm-paginate` library. A few updates had to be made to the Websites serializer as well in order to accommodate the pagination. 
Tags: pagination, nestjs, typeorm

Add pagination

---

package-lock.json
package.json

Why: Fix that adds paginate library to dependencies and removes from devDependencies.

Add paginate library to package.json

---

apps/api/src/parse-optional-int.pipe.spec.ts
apps/api/src/parse-optional-int.pipe.ts
apps/api/src/website/website.controller.ts

Why: Fix pagination issue by adding a new `Pipe` that parses ints and ignores `undefined`. Add tests.
Tags: Pagination, pipes, tests

Fix pagination bug

---

apps/scan-engine/src/scan-engine.consumer.ts
manifest.yml

Why: This is mostly some tuning after observing behavior in Cloud.gov for a bit. This bumps up the memory for the producer (which was experiencing Exit Code 137 on start) and the API. It also increases the instance number on the consumers and lowers the concurrency in the the individual processes.
How: Update the `ScanEngineConsumer` and the `manifest.yml` files. 
Tags: Infrastructure, tuning, performance, bugfix

Bump up memory and instances for consumer and producer

---

deploy-cloudgov.sh
libs/message-queue/src/config/mq.config.ts

Why: Cloud.gov is deprecating the Kubernetes-backed Redis and switching to AWS Elasticache Managed Redis. This updates to our version to the AWS Managed service. 
Tags: redis, elasticache, aws, cloud.gov
Closes https://github.com/18F/site-scanning/issues/801

Switch to AWS Managed Redis.

---

libs/message-queue/src/message-queue.module.ts

Why: After switching to AWS-Managed Elasticache Redis, all attempts to connect started hanging. The `BullModule` which we use for message queue management, uses `ioredis` behind the scenes to interface with Redis. 
Following the advice from [this GitHub Issue comment](https://github.com/luin/ioredis/issues/1042#issuecomment-575642093), fixed the connection issues.
Tags: redis, bugfix, tls, config, bull, elasticache, cloud.gov,

Bugfix: Redis connections hanging

---

libs/message-queue/src/config/mq.config.ts
libs/message-queue/src/message-queue.module.ts
package-lock.json
package.json

Why: This fixes the `start:all` issue in which races between the processes using `concurrently` would create some noise on start up. It also fixes an issue with the local development of the message queue, namely that connections to Redis were failing during local development. 
Tags: bugfix, message queue, concurrently, local development

Local Dev Bugfixes: start:all concurrency and message queue configuration

---

libs/message-queue/src/config/mq.config.ts
libs/message-queue/src/message-queue.module.ts

Why: This allows both local and prod message queue configuration to work.
Tags: bugfix, message queue, redis

Change message queue configuration.

---

entities/core-result.entity.ts

Why: `scan_date` was not updating. This fixes the column to populate on updates. 
Closes https://github.com/18F/site-scanning/issues/830

Fix scan date issue.

---

manifest.yml

Why: This sets the scanners to run at 00:00 server time. 
Tags: cron, scanners

Set cron schedule to midnight.

---

entities/core-result.entity.ts
libs/database/src/core-results/core-result.module.ts
libs/database/src/core-results/core-result.service.spec.ts
libs/database/src/core-results/core-result.service.ts
libs/database/src/solutions-results/solutions-result.service.spec.ts
libs/database/src/solutions-results/solutions-result.service.ts

Why: There was a bug in the way I was saving both `CoreResult`s and `SolutionsResult`s. This basically meant that the original `updated` date would always be persisted on updates to the database. This change uses the `insert` and `update` methods of the Typeorm repository so that the existing object is updated (or the new object is created). 
How: Change the `core-results-service` and `solutions-results-service`. Update the tests.
Tags: bugfix, typeorm, updated, core-result, solutions-result

Fix Date Issue: Pt. 2

---

apps/api/src/website/website-serializer.interceptor.ts
apps/producer/src/producer.module.ts
apps/producer/src/task/task.service.spec.ts
apps/producer/src/task/task.service.ts
deploy-cloudgov.sh
docker-compose.yml
entities/website.entity.ts
libs/datetime/src/datetime.module.ts
libs/datetime/src/datetime.service.spec.ts
libs/datetime/src/datetime.service.ts
libs/datetime/src/index.ts
libs/datetime/tsconfig.lib.json
libs/snapshot/src/index.ts
libs/snapshot/src/snapshot-save-options.interface.ts
libs/snapshot/src/snapshot.module.ts
libs/snapshot/src/snapshot.service.spec.ts
libs/snapshot/src/snapshot.service.ts
libs/snapshot/tsconfig.lib.json
libs/storage/src/config/storage.config.ts
libs/storage/src/index.ts
libs/storage/src/storage.module.ts
libs/storage/src/storage.service.spec.ts
libs/storage/src/storage.service.ts
libs/storage/tsconfig.lib.json
manifest.yml
nest-cli.json
package-lock.json
package.json
tsconfig.json

Why: This feature adds a JSON snapshot of the database to S3. This allows for bulk downloading from S3 (as opposed to through the API). It also archives any existing files and copies them to an `/archive` directory in S3. There is also a local version set up, that uses `minio` in place of S3.
How: This feature adds a few things to the codebase. 1) The `StorageService` which interfaces with S3, 2) The `SnapshotService` which is responsible for the logic of querying the database, and archival and storage into S3, 3) and the `DatetimeService` which mostly exists for making testing easier. 
The main public API to be concerned with is probably the `SnapshotService.weeklySnapshot()`. This is used by the `TaskService` which manages the cron logic. This is currently being called daily (while …

Add Bulk Download Feature

---

apps/cli/src/main.ts
apps/scan-engine/src/scan-engine.consumer.ts
deploy-cloudgov.sh
entities/website.entity.ts
libs/core-scanner/src/core-scanner.service.ts
libs/database/src/core-results/core-result.service.ts
libs/database/src/websites/dto/create-website.dto.ts
libs/database/src/websites/websites.service.spec.ts
libs/database/src/websites/websites.service.ts
libs/ingest/src/ingest.service.ts
libs/ingest/src/subdomain-row.interface.ts
libs/snapshot/src/snapshot.service.ts
libs/solutions-scanner/src/solutions-scanner.service.ts
libs/storage/src/storage.service.ts
run-ingest-cloud-gov.sh

Why: This adds the 25k target url list to the system -- this necessitated some changes to the `IngestService`. I also took the opportunity to clean up some issues with how the `IngestService` dealt with promises and with how the `ScanEngineConsumer` dealt with the message queue. As this increases the scale of the service by about 25x, I added a lot more logging to various services and event monitoring to the message queue consumer. 
A few other things to note: The 25k list has a slightly different schema, so I changed the `Website` entity schema to match. I added a convenience script for running the ingest task in Cloud.gov. 
Tags: ingest, target-url, logging, scan engine

Add new target url list.

---

apps/api/src/main.ts

Why: This enables CORS on the API.
Tags: cors, API

Enable CORS.

---

entities/solutions-result.entity.ts
libs/solutions-scanner/src/solutions-scanner.service.spec.ts
libs/solutions-scanner/src/solutions-scanner.service.ts
libs/solutions-scanner/test/app.e2e-spec.ts

Why: This adds the third party services fields to the `SolutionsScanner`. This basically builds on the DAP scan, which is why it's included with the SolutionsScanner for now. The basic methodology is to 1) capture any outbound requests from the website that aren't navigation requests and that aren't requests to the same domain as URL from which the requests are originating 2) dedupe and filter out any false-y requests. 
How: Update the SolutionScanner, update tests. Note: in the e2e tests I also added a few of the frequently-changing results to the expected object (which is unrelated to this work). 
Tags: third party services

Add Third Party Services fields.

---

apps/api/src/website/website.controller.ts
libs/database/src/websites/websites.service.ts
libs/ingest/src/ingest.service.ts

Why: This is related to the ingest of the 25k urls in which the schema changed slightly from before. The issue is that the previous dataset had all urls in upper case. This change ensures that they're ingested as lower case and queried as lower case. The more sustainable long-term way to do this is to likely use a `createQueryBuilder` and use something like `LOWER(url) = LOWER(:url)` in the Typeorm query. But, the tradeoff is losing the expressivity of the repository pattern. Additionally, this change adjusts the order of the Interceptors so that we get a 404 when the target URL doesn't exist. 
Tags: bugfix, ingest, api

Use to toLowerCase instead of toUpperCase. Fix order of interceptors.

---

libs/snapshot/src/snapshot.service.ts
manifest.yml

Why: The CSV arrays were being flattened into columns. This removes that and changes the snapshot schedule.

Bugfix: Don't flatten CSV arrays

---

apps/api/src/main.ts

Why: In order to get Swagger requests to work, add a prefix for the dev stage. 
Tags: Swagger, open api

Add global prefix when on dev stage.

---

apps/api/src/main.ts
apps/producer/src/main.ts
apps/scan-engine/src/main.ts
apps/scan-engine/src/scan-engine.consumer.ts
manifest.yml

Why: Add log levels for `dev` and non-`dev`. Turn on `OPTIMIZE_MEMORY` environment variable. Lower concurrency number and up instance number.
Tags: logging, memory, cloud.gov

Add log levels and change memory and instance number.

---

apps/scan-engine/src/main.ts
apps/scan-engine/src/scan-engine.consumer.ts
manifest.yml

Why: This updates the logging so that the consumer logs its status to the `log` log level. 
Tags: logging, consumer

Logging updates

---

apps/producer/src/main.ts
apps/producer/src/task/task.service.ts

Why: Switch task service to log using `log` log level. 
Tags: Logging, Task Service

Add logging to task service.

---

libs/database/src/websites/websites.service.ts

Why: Change the API sort order to be alphabetical.
Tags: API, sort

Change sort order.

---

apps/producer/src/task/task.service.spec.ts
apps/producer/src/task/task.service.ts
libs/database/src/websites/websites.service.spec.ts
libs/database/src/websites/websites.service.ts
libs/snapshot/src/snapshot.service.spec.ts
libs/snapshot/src/snapshot.service.ts

Why: This adds a method to the `WebsiteService` that returns website data alone, rather than with the join results. 
Tags: WebsiteService

Add method for website data only.

---

entities/solutions-result.entity.ts

Why: This returns `null` if there aren't any robots.txt sitemap locations. 
Closes https://github.com/18F/site-scanning/issues/844

Return null if there aren't any robots.txt sitemaps.

---

manifest.yml

Why: This set the snapshot job to run weekly on Sunday. 
Tags: Snapshot, cron

Set snapshot to Sunday

---

cloudgov-deploy.sh

Why: Small bug in the deploy script because of the `set u` settings.
How: Using variable expansion to pass manifest.
Tags: bug

Fix deploy script

---

.github/workflows/deploy.yml

Why: This adds a scheduled redeploy of the application every 24 hours.
How: It uses GitHub Actions to redeploy the action at 10:15PM UTC
Tags: CI/CD

Add a scheduled redeploy.

---

manifest-dev.yml

Why: We need to use less memory in Cloud.gov.
How: update the manifest-dev.yml file.
Tags: IaC

Update dev manifest for smaller footprint.

---

libs/database/src/database.module.ts

Per https://github.com/GSA/site-scanning/issues/110, we need to configure SSL/TLS for PostgreSQL and Redis.  Redis already uses TLS in non-dev environments (see https://github.com/GSA/site-scanning-engine/blob/main/libs/message-queue/src/message-queue.module.ts#L22 ) so this ought to be the one and only change to resolve that issue.
The source for the SSL requirement change came from Stack Overflow:
https://stackoverflow.com/questions/56660312/cannot-connect-an-ssl-secured-database-to-typeorm/63043606#63043606

Enforce SSL when interacting with PostgreSQL

---

docs/environment_provisioning.md
site_scanner_endpoint_test.bash

This is for [134](https://github.com/GSA/site-scanning/issues/134) (document dev environment); it includes documentation in markdown plus a script used to create test requests to the API directly using `curl`.  The script fetches stuff like the route, the API key, etc. automatically so one need only run `./site_scanner_endpoint_test.bash`.

134 document dev environment

---

.github/workflows/restart-worker.yml

Create Github Action workflow to restart scan consumers 10 minutes before daily enqueue job.
This moves the "enqueue-scans" job forward 10 minutes, and runs the restart job daily at 00:00 UTC.

Restart worker Github Action workflow

---

entities/scan-status.ts
notebooks/README.md
notebooks/scan-date-analysis.ipynb

Fix issue where undefined error messages lead to scan results not being saved to the database. See: https://github.com/GSA/site-scanning/issues/201
Also, add Jupyter notebook to compare domains with old scan dates against the target URL list. This is a useful way to analyze data and seems worth checking in for future analysis/debugging work.

Fix issue with site data not saving to the database

---

apps/cli/src/ingest.controller.spec.ts
apps/cli/src/ingest.controller.ts
apps/cli/src/main.ts
entities/core-result.entity.ts
entities/website.entity.ts
libs/database/src/websites/websites.service.spec.ts
libs/database/src/websites/websites.service.ts
libs/ingest/src/ingest.service.spec.ts
libs/ingest/src/ingest.service.ts
manifest.yml
notebooks/scan-result-quantity-analysis.ipynb

Issue: https://github.com/GSA/site-scanning/issues/129
Goal: The `website` and `core_results` database tables should only include websites that are listed in the CSV file of valid website URLs.
Solution: The CLI app's `ingest` command now removes extraneous websites from the database after ingesting the current CSV list of websites by calling the ingest service's new `removeOldUrls` method.

Cleanup on ingest

---

.github/workflows/ingest.yml
apps/cli/src/ingest.controller.ts
apps/cli/src/main.ts
libs/ingest/src/config/ingest.config.ts
libs/ingest/src/ingest.module.ts
libs/ingest/src/ingest.service.spec.ts
libs/ingest/src/ingest.service.ts

This PR lets users override the default list of valid federal subdomains when prompting the system to ingest that list.
- Moved hard-coded URL for list of valid federal subdomains to a config file for the `ingest` feature
- Users can pass an optional `url` argument to the CLI's `ingest` action
- This argument can also be passed by way of the **Ingest website list** GitHub action

Update ingest CLI to accept optional url argument

---

docs/libraries/ingest.md

Related Issue: https://github.com/GSA/site-scanning/issues/109
Added documentation specifying exactly where the default URL for the list of valid federal subdomains lives in the ingest library, and how to override that default.

Add documentation for ingest library

---

libs/core-scanner/src/core-scanner.module.ts
libs/core-scanner/src/core-scanner.service.spec.ts
libs/core-scanner/src/core-scanner.service.ts
libs/core-scanner/src/pages/not-found.ts
libs/ingest/src/ingest.module.ts
libs/ingest/src/ingest.service.spec.ts
libs/ingest/src/ingest.service.ts
package-lock.json
package.json

Issue: https://github.com/GSA/site-scanning/issues/133
Install `nest/axios` and use the `HttpModule` and `HttpService` from that package instead of `nest/common`.

Upgrade to nest/axios for http services

---

libs/database/src/websites/websites.service.integration.spec.ts
libs/database/src/websites/websites.service.ts
libs/snapshot/src/snapshot.service.spec.ts
libs/snapshot/src/snapshot.service.ts

This PR updates the query that retrieves websites for the live snapshot to filter out entries that have a final_url_mimetype of any of the following:
- application/xhtml+xml
- application/xml
- application/json
- text/xml

Update query for live snapshot

---

libs/core-scanner/src/scans/dap.spec.ts
libs/core-scanner/src/scans/dap.ts

This PR updates the logic used to determine whether or not DAP usage is detected in a given site.
Previously, `dap_detected_final_url` was found to be true only if either of the IDs below were used in an outbound request:
- `'UA-33523145-1'`
- `'G-9TNNMGP8WJ'`
After this change, `dap_detected_final_url` is now true if either of those IDs are used in an outbound request, **or** if parameters are passed with an outbound request to Universal-Federated-Analytics-Min.js.

Update dap scan logic

---

libs/database/src/websites/websites.service.integration.spec.ts
libs/database/src/websites/websites.service.spec.ts
libs/database/src/websites/websites.service.ts
libs/snapshot/src/snapshot.service.spec.ts
libs/snapshot/src/snapshot.service.ts

This PR adds filters to the website service to ensure that only websites with a top level domain of 'gov' are returned.

Add tld filter to website service

---

entities/core-result.entity.ts
libs/snapshot/src/serializers/json-serializer.spec.ts

https://github.com/GSA/site-scanning/issues/562
This PR updates two fields in the CoreResult entity class so that they are returned as arrays instead of comma-separated strings.
- cookie_domains
- login_detected

Core result entity update

---

libs/core-scanner/src/pages/security.ts

This PR updates the security scan so that a redirect with any valid 3xx HTTP response code will be checked for https redirection.

Update security scan to accept any valid 3xx HTTP response code

---

libs/database/src/core-results/core-result.service.ts

Fix the method updating a core result scan's URL scan results to set `finalUrlTopLevelDomain` to `null` if the primary scan fails.

Fix method updating core result URL scan results

---

libs/core-scanner/src/pages/primary.spec.ts
libs/core-scanner/src/pages/robots-txt.ts
libs/core-scanner/src/pages/sitemap-xml.ts
libs/core-scanner/src/scans/url-scan.ts
libs/core-scanner/src/util.ts

Previously, the sitemap and robotstxt scans were only registering that those pages were live if the response code was 200 exclusively. In this update, those scans now register those pages as live if any valid 2xx family response code is detected.

Move isLive to util and apply to sitemap and robots scans

---

libs/core-scanner/src/scans/seo.ts

Update seo scan to also check http response headers for hreflang codes

seo scan update

---

.gitignore
apps/cli/src/app.module.ts
apps/cli/src/main.ts
apps/cli/src/security-data.controller.ts
entities/core-result.entity.ts
entities/scan-data.entity.ts
entities/scan-page.entity.ts
libs/core-scanner/src/core-scanner.module.ts
libs/core-scanner/src/core-scanner.service.spec.ts
libs/core-scanner/src/core-scanner.service.ts
libs/database/src/core-results/core-result.service.spec.ts
libs/database/src/core-results/core-result.service.ts
libs/security-data/src/config/security-data.config.ts
libs/security-data/src/data-fetcher.ts
libs/security-data/src/index.ts
libs/security-data/src/security-data.module.ts
libs/security-data/src/security-data.service.ts
libs/security-data/tsconfig.lib.json
package.json
tsconfig.json

- Create a `security-data` library to:
- Handle ingestion of security data CSV file
- Provide access point for scanner to use in order to retrieve security results
- Incorporate security data points into `core-scanner` lib's service's main routine
- Add CLI command that we can hook into via GitHub Actions to reingest the security data CSV file on a regular basis

Implement basic security data integration

---

libs/core-scanner/src/pages/sitemap-xml.ts

Per item number 2 in https://github.com/GSA/site-scanning/issues/918, change the sitemap detected logic to make sure `/sitemap.xml` is at the end of the URL's path, not the entire path.

Update sitemap xml detected logic

---

libs/core-scanner/src/pages/primary.ts
libs/core-scanner/src/scans/required-links.spec.ts
libs/core-scanner/src/scans/required-links.ts

Refactor required links scan to use puppeteer page instead of regex.

Required Links Scan Refactor

---

.github/workflows/enqueue-limited-scans.yml
apps/cli/src/main.ts
apps/cli/src/queue.controller.ts

Add functionality to queue up a limited number of websites to scan
A new cli function *enqueue-limited-scans* has been added. It accepts 1 argument *--limit <number>*

Add functionality to specify a website limit to enqueue scans

---

libs/logging/src/config/pino-config.ts
libs/logging/src/config/pino-pretty-config.ts

Rename `logTime` field to `sseLogTime` to eliminate field collisions in Logstash

Update logTime field

---

.github/workflows/enqueue-site.yml
apps/cli/src/main.ts
apps/cli/src/queue.controller.ts

Introduce a new `enqueue-site` CLI command for enqueuing a specific site to the scan queue. Additionally, a new GitHub Actions workflow has been added, enabling users to specify a URL for queuing in the scan process.

Add Enqueue-Site CLI Command and GitHub Actions Workflow

---

libs/core-scanner/src/core-scanner.service.ts
libs/core-scanner/src/pages/primary.ts
libs/core-scanner/src/util.ts

This pull request enhances page load handling and logging capabilities. The key changes include:
- Switching waitUntil to networkidle2 for more reliable page load detection.
- Adding metadata to log redirect chains and failure reasons for better traceability.
- Passing job metadata to page scans for improved context in log entries.
These updates aim to improve the accuracy and clarity of page load events and related diagnostics.

Improve Page Load Handling and Logging: Update waitUntil, Add Redirect/Failure Metadata

---

libs/core-scanner/src/util.ts

This change eliminates the usage of errorText from request.failure() which was causing an undefined error in certain cases. This ensures more stable error handling and prevents runtime issues related to undefined values.

Update requestfailed meta to prevent undefined error.

---

libs/browser/src/puppeteer.service.ts
package-lock.json
package.json

This PR reverts the recent update to the Puppeteer version, as it has been causing unexpected browser crashes in our environment. After thorough investigation, it was identified that the newer version introduced instability, leading to frequent failures during automated browser tasks.

Revert Puppeteer update
